### ISSUE TITLE
not able to run on macOS

### ISSUE THREAD

**Issue by hannesa2** [kurron/docker-firefox#3]
Unfortunately this is not able to run on macOS  `./run.sh` deliveres

```
./run.sh: line 5: getent: command not found
./run.sh: line 6: getent: command not found
access control disabled, clients can connect from any host
...
...
docker: Error response from daemon: linux runtime spec devices: error gathering device information while adding custom device "/dev/snd": no such file or directory.
```

`/dev/snd` and command `getent` are not known to macOS

after I simply removed this from `Dockerfile` I can't connect to X11 again

> access control disabled, clients can connect from any host
> docker run --env HOME=/home/powerless --env DISPLAY=unix/private/tmp/com.apple.launchd.1tJmaJWJrr/org.macosforge.xquartz:0 --interactive --name Firefox --net host --rm --tty --volume /tmp/.X11-unix:/tmp/.X11-unix --volume /var/run/docker.sock:/var/run/docker.sock --workdir /home/powerless kurron/docker-firefox:latest
> Failed to connect to Mir: Failed to connect to server socket: No such file or directory
> Unable to init server: Broadway display type not supported: unix/private/tmp/com.apple.launchd.1tJmaJWJrr/org.macosforge.xquartz:0
> Error: cannot open display: unix/private/tmp/com.apple.launchd.1tJmaJWJrr/org.macosforge.xquartz:0
>

**Comment by kurron** [comment]
Unfortunately, I don't have access to a Mac so I won't be able to debug this. :crying_cat_face:
